server:
  port: 8081

spring:    
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: "alertCreation:com.soc.soar.dataservice.exchange.request.AuditLogRequestDTO,emailRequest:com.soc.soar.dataservice.exchange.request.EmailRequestDTO"

app:
  swagger:
    serverUrl: http://10.6.0.11:8087/data
 

springdoc:
  swagger-ui:
    config-url: data/v3/api-docs/swagger-config
    url: data/v3/api-docs
    enabled: true